apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessing-deployment
spec:
  selector:
    matchLabels:
      app: orderprocessingapp
  replicas: 3
  template:
    metadata:
      name: orderprocessor
      labels:
        app: orderprocessingapp
    spec:
      containers:
      - image: pratikdas/orderprocessing:latest
        name: orderprocessing