apiVersion: v1
kind: Pod
metadata:
 name: orderprocessingpod
 namespace: default
spec:
 containers:
   - name: orderprocessing
     image: pratikdas/orderprocessing
     ports:
       - containerPort: 8080
         protocol: TCP
     resources:
       limits:
         memory: "200Mi"
       requests:
         memory: "100Mi"