apiVersion: v1
kind: Pod
metadata:
  name: orderprocessingpod-v2
  namespace: default
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - name: orderprocessing
      image: pratikdas/orderprocessing
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"